### PR TITLE
Improved Dutch translation

### PR DESCRIPTION
**Pull request by 304NotModified**
"Directory" isn't a Dutch word. It was already partly replaced by "map".

I've replaced them manually (no replace all) - I checked them all by hand

Also "gronddirectory" is really LOL

### CODE REVIEW

**Comment by martinprikryl** [comment]
Thanks. I have forwarded this to Dutch translator of WinSCP.

**Comment by martinprikryl** [comment]
These changes were uploaded by this commit:
https://github.com/martinprikryl/winscp/commit/7cc335994c7a7aa736fb09de6f3b01b8a35a6a03

**Comment by martinprikryl** [comment]
Thanks for your suggestion.

**Comment by 304NotModified** [comment]
Thanks for checking/integrating this!

**Pull request closed without merging**
